# Generated by Django 2.2.1 on 2019-06-07 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20190607_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='managers',
            new_name='manager',
        ),
    ]
